name: Node.js CI

on:
  push:
    branches: [ main ]
    
jobs:
  build:

    runs-on: self-hosted

#     strategy:
#       matrix:
#         node-version: [12.x, 14.x, 16.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - run: sudo docker rm -f luckyjing
    - run: sudo docker ps
# - run: docker rmi nginx:stable-alpine
    - run: npm i
    - run: npm run build
    - run:  sudo docker run -d -p 80:80 --name luckyjing -v /home/int209/LuckyJingByKimmie/luckyjing.conf:/etc/nginx/conf.d/default.conf -v/home/int209/LuckyJingByKimmie/dist:/usr/share/nginx nginx
